version: '3'
services:
  web:
    environment:
      OTBP_SETTINGS: "/app/env/docker.env"
    build: .
    ports:
      - "8099:80"
    restart: always
    volumes:
      - ${PWD}/otbp/prod.db:/app/otbp/prod.db

